title: Ah-Maze-Ing
description: Addictive retro maze puzzle game for iPhone
show_downloads: false
google_analytics: 'G-03FCE55ZMM'

repository: Ah-Maze-Ing/Ah-Maze-Ing.github.io

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: true

plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - assets/bootstrap
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

